flags: {}
packages:
- '.'

extra-deps: ["scotty-tls-0.4.0"]
resolver: nightly-2015-12-05

image:
  container:
    base: "ga2arch/base:latest"
    name: "ga2arch/ga2bot"
    entrypoints:
     - ga2bot
